variables:
  MAJOR_VERSION: "1"

stages:
  - tag-release

tag-release:
  stage: tag-release
  image: curlimages/curl

  script:
    - curl --location --silent --request POST "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${MAJOR_VERSION}.$(date +%-j).${CI_PIPELINE_IID}&ref=master" --header "PRIVATE-TOKEN:${GITLAB_TOKEN}"
  only:
    - master